### PR TITLE
use maelstrom flavoured template

### PR DESCRIPTION
**Pull request by meek0**

### CODE REVIEW

**Comment by ymarcon** [comment]
Why?

**Comment by meek0** [comment]
This template would be used for all maelstrom reports. From what I understand, it is based on a template that is already used for some maelstrom papers.

**Comment by ymarcon** [comment]
But OBiBa is not MR. MR uses OBiBa which means that the OBiBa tool should be configurable to match the needs of MR. Other users probably do not want the MR output.

**Comment by meek0** [comment]
True

**Pull request closed without merging**
